name: Build UkuleleAkkordtrainer

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '*.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
          pip install pyinstaller

      - name: Build .exe file
        run: pyinstaller main.py --onefile

      - name: Copy akkorde.json next to .exe
        run: cp akkorde.json dist/

      - name: Check dist folder
        run: ls -la dist/

      - name: Create zip archive
        run: |
          cd dist
          ls -la  # zur Sicherheit anzeigen
          zip UkuleleAkkordtrainer.zip main akkorde.json
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Automatisch erstelltes Release.

            **Hinweis:** Diese Version laeuft aktuell nur unter Windows.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload zip to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: dist/UkuleleAkkordtrainer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
