name: Build UkuleleAkkordtrainer

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build exe
        run: pyinstaller main.py --onefile

      - name: Copy akkorde.json next to exe
        run: cp akkorde.json dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UkuleleAkkordtrainer
          path: dist/
